package org.chromium.alloy.adb.shell;

import java.nio.channels.Pipe.SinkChannel;
import java.nio.channels.Pipe.SourceChannel;
import java.util.Map;

/**
 * TODO: Insert description here. (generated by penghuang)
 */
public class GetOptCommand extends Command {
  public GetOptCommand(String[] args, String cwd, Map<String, String> envs,
      SourceChannel input, SinkChannel output) {
    super(args, cwd, envs, input, output);
  }  
}
