package org.chromium.alloy.adb;

/**
 * TODO: Insert description here. (generated by penghuang)
 */
public class Adb {
  /**
   * @param args
   */
  public static void main(String[] args) {
    AdbServer.start();
    AdbServer.shutdown();
  }
}
