package org.chromium.alloy.adb;

/**
 * TODO: Insert description here. (generated by penghuang)
 */
class AdbRemoteSocket extends AdbSocket {
  private Transport mTransport = null; 

  public AdbRemoteSocket(int id, Transport transport) {
    mId = id;
    mTransport = transport;
  }
  
  @Override
  public void ready() {
    AdbMessage message = new AdbMessage(AdbMessage.A_OKAY, mId, mPeer.mId, "");
    mTransport.send(message);
  }

  @Override
  public int enqueue(AdbMessage message) {
    message.command = AdbMessage.A_WRTE;
    message.arg0 = mPeer.mId;
    message.arg1 = mId;
    mTransport.send(message);
    return 1;
  }

  @Override
  public void close() {
    AdbMessage message = new AdbMessage(AdbMessage.A_CLSE, 0, mId, "");
    if (mPeer != null) {
      message.arg1 = mPeer.mId;
      mPeer.mPeer = null;
      mPeer.close();
    }
    mTransport.send(message);
  }

}
