package org.chromium.alloy.adb;

import java.io.IOException;

/**
 * TODO: Insert description here. (generated by penghuang)
 */
interface IOChannel {
  public abstract void onAcceptable() throws IOException;
  
  public abstract void onReadable() throws IOException;
  
  public abstract void onWritable() throws IOException;
}
