package org.chromium.alloy.adb;

/**
 * TODO: Insert description here. (generated by penghuang)
 */
class JDWPService extends AdbSocket {
  private int mPass = 0;

  private String listProcess() {
    // TODO(penghuang): returns processes.
    return "";
  }
  
  @Override
  public void ready() {
    if (mPass == 0) {
      AdbMessage message = new AdbMessage();
      message.setData(listProcess());
      mPeer.enqueue(message);
      mPass++;
    } else {
      mPeer.close();
    }
  }

  @Override
  public int enqueue(AdbMessage message) {
    mPeer.close();
    return -1;
  }

  @Override
  public void close() {
    AdbSocket peer = mPeer;
    if (peer != null) {
      mPeer = null;
      peer.close();
    }
  }
}
